#!/bin/bash

COMMIT_MESSAGE_FORMAT="^JIRA-([0-9]+)(.*)$"

validate_commit_message_format() {
  if ! [[ $1 =~ $COMMIT_MESSAGE_FORMAT ]]; then
    echo_error "Commit message validation failed. (it does not contain a JIRA task id)"
    exit 1
  fi
}

echo_error() {
  echo -e "\e[0;31m$1\e[0m" >&2
}

validate_commit_message_format
exit 0